{{- if .Values.secrets.enabled }}
{{- if or .Values.secrets.toEnv .Values.secrets.toFiles }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app-stateful.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: {{ .Values.secrets.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.secretStoreRef.kind | quote }}
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - find:
      tags:
        {{ include "app-stateful.fullname" . }}: "true"
{{- range .Values.secrets.toFiles }}
  - find:
      name:
        regexp: {{ .name | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.secrets.toEnvironments }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app-stateful.fullname" . }}-secrets-env
spec:
  secretStoreRef:
    name: {{ .Values.secrets.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.secretStoreRef.kind | quote }}
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
{{- range .Values.secrets.toEnvironments }}
  - extract:
      key: {{ .name | quote }}
{{- end }}
{{- end }}
{{- end }}
