name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Create Helm Repository Structure
        run: |
          # Create repository structure without .tgz files
          mkdir -p repo
          
          # Copy all charts to versioned directories
          find charts -maxdepth 1 -type d ! -path charts -name "*" | while read chart_dir; do
            if [ -f "$chart_dir/Chart.yaml" ]; then
              chart_name=$(grep '^name:' "$chart_dir/Chart.yaml" | cut -d' ' -f2)
              chart_version=$(grep '^version:' "$chart_dir/Chart.yaml" | cut -d' ' -f2)
              
              # Create versioned directory structure
              version_dir="repo/$chart_name/$chart_version"
              mkdir -p "$version_dir"
              
              # Copy chart source files (no packaging)
              cp -r "$chart_dir"/* "$version_dir/"
              
              echo "Created $chart_name version $chart_version at $version_dir"
            fi
          done
          
          # Generate index.yaml for Helm repository compatibility
          cat > repo/index.yaml << 'EOF'
          apiVersion: v1
          entries:
          EOF
          
          # Build index entries for all charts
          find charts -maxdepth 1 -type d ! -path charts -name "*" | while read chart_dir; do
            if [ -f "$chart_dir/Chart.yaml" ]; then
              chart_name=$(grep '^name:' "$chart_dir/Chart.yaml" | cut -d' ' -f2)
              chart_version=$(grep '^version:' "$chart_dir/Chart.yaml" | cut -d' ' -f2)
              chart_description=$(grep '^description:' "$chart_dir/Chart.yaml" | cut -d' ' -f2- | tr -d '"')
              chart_type=$(grep '^type:' "$chart_dir/Chart.yaml" | cut -d' ' -f2 || echo "application")
              
              timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              
              # Check if this chart already exists in index
              if ! grep -q "^  $chart_name:" repo/index.yaml; then
                echo "  $chart_name:" >> repo/index.yaml
              fi
              
              # Add version entry
              cat >> repo/index.yaml << EOF
          - apiVersion: v2
            created: "$timestamp"
            description: "$chart_description"
            name: $chart_name
            type: $chart_type
            urls:
            - https://osnatashush.github.io/tratix-helm-chart/$chart_name/$chart_version
            version: $chart_version
          EOF
            fi
          done
          
          echo "generated: \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"" >> repo/index.yaml
          
          # Show what we created
          echo "Repository structure:"
          find repo -type f | head -20
          
          echo "Generated index.yaml:"
          cat repo/index.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './repo'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
