name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: apps
          config: cr.yaml

      - name: Package and Index Charts
        run: |
          # Create charts directory if it doesn't exist
          mkdir -p charts
          
          # Package all charts found in apps subdirectories
          find apps -name Chart.yaml -exec dirname {} \; | while read chart_dir; do
            echo "Packaging chart in: $chart_dir"
            helm package "$chart_dir" -d charts/
          done
          
          # List packaged charts
          ls -la charts/
          
          # Generate index
          helm repo index charts --url https://osnatashush.github.io/tratix-helm-chart/charts
          
          # Copy to root for GitHub Pages
          cp charts/index.yaml .
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          destination_dir: charts
